variables:
- group: EDK Build Settings
- name: workDir
  value: '$(Build.SourcesDirectory)/ci-wex-build'

resources:
  repositories:
  - repository: self
    type: github
    ref: trunk
  - repository: ci-wex-build
    type: github
    endpoint: PTC
    name: wincomplm/ci-wex-build
    ref: main

jobs:

- job: Job_1
  displayName: Build JUnit
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    clean: True
  - checkout: ci-wex-build
  - task: JavaToolInstaller@0
    displayName: Use Java 11
    inputs:
      versionSpec: 11
      jdkArchitectureOption: x64
      jdkSourceOption: PreInstalled
  - task: ReplaceInFilesTextByText@2
    displayName: Update settings
    inputs:
      parameterSearchDirectory: $(workDir)/build
      parameterSearchText: '[password]'
      parameterReplaceText: $(support-wex-pwd)
      parameterFilesPattern: '*.xml'
  - task: CopyFiles@2
    displayName: Move settings.xml
    inputs:
      SourceFolder: $(workDir)/build
      Contents: settings.xml
      TargetFolder: C:\Users\VssAdministrator\.m2
      OverWrite: true
  - task: Maven@2
    displayName: JUnit Build 12.1
    inputs:
      mavenPOMFile: wex-junit/pom.xml
      goals: clean install
      options: '-P 12.1 -Dcve.check.skip=true -Djar.sign=true -Dwex.sign=true -Dobfuscate=false -Denv.ZKM_HOME=$(workDir)/zkm'
  - task: CopyFiles@2
    displayName: Copy Files Staging
    condition: succeededOrFailed()
    inputs:
      SourceFolder: $(system.defaultworkingdirectory)
      Contents: '**/*.wex'
      TargetFolder: $(build.artifactstagingdirectory)
  - task: PowerShell@2
    displayName: Upload to teams
    inputs:
      filePath: $(workDir)/build/uploadToSharePointFilePath.ps1
      arguments: '-SPVersion "Online" -SPUsername $(sp.user) -SPPassword $(sp.pwd) -SPURL https://wincomconsulting.sharepoint.com/sites/EDK-External -SPFolder /Documentos%20compartidos/General/JUnit -Folder $(build.artifactstagingdirectory)' 
